version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/laravel_project
    overwrite: yes

hooks:
  BeforeInstall:
    - location: scripts/full_cleanup_before_install.sh # A new script to delete existing deploy.sh
      timeout: 300
      runas: root # Might need root to remove files in /var/www/html

  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 180
      runas: ec2-user
