version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1 # This tells CodeBuild to use PHP 8.1
    commands:
      - echo "--- BUILD INITIATED WITH LATEST BUILDSPEC VERSION X.X ---" # <-- Add this line
      - echo "Installing Composer..."
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo "Installing Composer dependencies..."
      - composer install

  pre_build:
    commands:
      - echo "Pre-build phase (e.g., running tests)"

  build:
    commands:
      - echo "Build phase (e.g., compiling assets, application build steps)"

  post_build:
    commands:
      - echo "Post-build phase (e.g., deployment, cleanup)"

artifacts:
  files:
    - '**/*' # This packages all files as the build artifact. Adjust as needed.
