version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing Composer dependencies..."
      - composer install


  pre_build:
    commands:
      - echo "Generating app key..."
      - php artisan key:generate

  build:
    commands:
      - echo "Running database migrations..."
      - php artisan migrate --force || true

  post_build:
    commands:
      - echo "Build completed!
      - echo Installing dependencies...
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer install
  pre_build:
    commands:
      - echo Pre-build steps...
      - cp .env.example .env || true
      - php artisan key:generate || true
  build:
    commands:
      - echo Laravel application build completed.


artifacts:
  files:
    - '**/*'

  discard-paths: no
=======

>>>>>>> 4ed8d54 (Add buildspec.yml for CodeBuild)
