version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing Composer..."
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo "Installing Composer dependencies..."
      - composer install

  pre_build:
    commands:
      - echo "Setting up environment..."
      - cp .env.example .env || true
      - php artisan key:generate || true

  build:
    commands:
      - echo "Running migrations..."
      - php artisan migrate --force || true
      - echo "Laravel application build completed."

  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files:
    - '**/*'
  discard-paths: no

