version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing Composer dependencies..."
      - composer install


  pre_build:
    commands:
      - echo "Generating app key..."
      - php artisan key:generate

  build:
    commands:
      - echo "Running database migrations..."
      - php artisan migrate --force || true

  post_build:
    commands:
      - echo "Build completed!"

artifacts:
  files:
    - '**/*'
  discard-paths: no
