version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1 # This is the ONLY line needed to tell CodeBuild to use PHP 8.1
    commands:
      # No 'phpenv install' here. CodeBuild handles it.
      - echo "Dependencies will be installed here if needed (e.g., composer install)"

  build:
    commands:
      - echo "Build steps will go here."

artifacts:
  files:
    - '**/*' # Adjust this as needed for your build output.
