version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1 # This tells CodeBuild to use PHP 8.1
    commands:
      - echo "--- BUILD INITIATED WITH LATEST BUILDSPEC VERSION X.X ---"
       - cd $CODEBUILD_SRC_DIR # ✅ Change to the project root
      - echo "Installing Composer..."
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo "Ensuring bootstrap/cache exists and is writable..."
      # Add these lines to ensure cache directory exists and is writable
      - mkdir -p bootstrap/cache
      - mkdir -p storage/framework/views
      - mkdir -p storage/framework/cache
      - mkdir -p storage/logs
      - chmod -R 777 bootstrap/cache # Add this line
      - chmod -R 777 storage

      # Remove abandoned swiftmailer package if present
      - echo "Removing swiftmailer..."
      - composer remove swiftmailer/swiftmailer || true

      # Add symfony/mailer and required dependencies
      - echo "Installing symfony/mailer..."
      - composer require symfony/mailer symfony/http-client
      
      # ✅ Composer install with scripts disabled and superuser allowed
      - echo "Installing dependencies without scripts (as root)..."
      - COMPOSER_ALLOW_SUPERUSER=1 composer install --no-scripts --no-interaction --prefer-dist

      - echo "Running post-install artisan scripts manually..."
      - php artisan package:discover

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Setting up environment..."
      - cp .env.example .env || true
      - php artisan key:generate || true

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Running migrations..."
      - php artisan migrate --force || true
      - echo "Laravel application build completed."

  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Build completed!"

artifacts:
  files:
    - '**/*' # This packages all files as the build artifact. Adjust as needed.
    discard-paths: no
