version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1 # This tells CodeBuild to use PHP 8.1
    commands:
      # DO NOT PUT 'echo "Installing custom PHP version..."' HERE
      # DO NOT PUT 'phpenv install 8.1' HERE
      # These lines must be REMOVED from your buildspec.yml
      # Any other installation commands, like composer install, would go here.
      - echo "PHP 8.1 is now set up by CodeBuild. Proceeding with other installations..."
      # Example: - composer install --no-interaction --prefer-dist

  pre_build:
    commands:
      - echo "Pre-build phase (e.g., running tests)"

  build:
    commands:
      - echo "Build phase (e.g., compiling assets, application build steps)"

  post_build:
    commands:
      - echo "Post-build phase (e.g., deployment, cleanup)"

artifacts:
  files:
    - '**/*' # This packages all files as the build artifact. Adjust as needed.
