version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "--- BUILD INITIATED WITH LATEST BUILDSPEC VERSION X.X ---"
      - cd $CODEBUILD_SRC_DIR # Change to the project root
      - echo "Installing Composer..."
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      
      # --- IMPORTANT: Ensure .env and key are set up BEFORE composer install and artisan commands ---
      - echo "Setting up environment and generating application key..."
      - cp .env.example .env || true # Copy .env.example, ignore if it doesn't exist
      - php artisan key:generate || true # Generate application key, ignore if it fails (e.g., already exists)
      # --- End of .env and key setup ---

      - echo "Ensuring bootstrap/cache and storage directories exist and are writable..."
      - mkdir -p bootstrap/cache
      - mkdir -p storage/framework/views
      - mkdir -p storage/framework/cache
      - mkdir -p storage/logs
      - chmod -R 777 bootstrap/cache
      - chmod -R 777 storage

      - echo "Removing swiftmailer if present..."
      - composer remove swiftmailer/swiftmailer || true

      - echo "Installing symfony/mailer and required dependencies..."
      - composer require symfony/mailer symfony/http-client --no-interaction

      - echo "Installing dependencies without scripts (as root)..."
      - COMPOSER_ALLOW_SUPERUSER=1 composer install --no-scripts --no-interaction --prefer-dist

      - echo "Dumping Composer autoload files..."
      - composer dump-autoload

      - echo "Clearing Laravel caches before package discovery..."
      - php artisan config:clear || true # Clear config cache
      - php artisan cache:clear || true  # Clear application cache
      - php artisan view:clear || true   # Clear view cache

      - echo "Running post-install artisan scripts manually (package:discover)..."
      - php artisan package:discover

  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Pre-build phase complete." # No specific commands needed here anymore as .env setup moved

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Running migrations..."
      - php artisan migrate --force || true
      - echo "Laravel application build completed."

  post_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - echo "Build completed!"

artifacts:
  files:
    - '**/*' # This packages all files as the build artifact. Adjust as needed.
  discard-paths: no
