version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1 # CodeBuild will attempt to set up PHP 8.1 for you
    commands:
      # Add any other installation commands here, e.g., Composer, npm, etc.
      - echo "Installing dependencies..."
      - composer install --no-interaction --prefer-dist

  pre_build:
    commands:
      - echo "Running pre-build checks..."
      # Add any pre-build commands like linting, testing, etc.

  build:
    commands:
      - echo "Building the application..."
      # Add your build commands here, e.g., compiling assets, running tests, etc.
      - # Example: For a simple PHP application, you might not have a complex "build" step.
        # You might just be moving files or running framework-specific commands.

  post_build:
    commands:
      - echo "Build completed on `date`"
      # Add any post-build commands, e.g., cleaning up, deploying, etc.

artifacts:
  files:
    - '**/*' # This will include all files from your source directory in the artifact
  # You can be more specific about what files to include, e.g.,
  # - 'dist/**/*'
  # - 'appspec.yml'
  # - 'index.php'
  # base-directory: 'dist' # If your build output is in a 'dist' folder
